version: '3.5'

services:
    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile
        container_name: property-backend
        environment:
            - PORT=2000
            - DB_HOST=db
            - DB_NAME=property_db
            - DB_USER=root
            - DB_PASS=root123
            - NODE_ENV=development
            - JWT_SECRET=HJZwd2wiOtjsNZDhqEBf
            - JWT_ACCESS_EXPIRATION_MINUTES=5
            - JWT_REFRESH_EXPIRATION_DAYS=30
            - LOG_FOLDER=logs/
            - LOG_FILE=%DATE%-app-log.log
            - LOG_LEVEL=error

        ports:
            - '2000:2000'
        command: sh -c "npm install && npm start"

        volumes:
            - ../backend:/app
        depends_on:
            - db

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: property-frontend
        environment:
            - APP_ACCESS_TOKEN="token"
            - APP_REFRESH_TOKEN="refresh"
        ports:
            - '3000:3000'
        command: sh -c "npm install &&  npm run dev"

        volumes:
            - ../frontend:/app
        depends_on:
            - backend

    db:
        image: postgres:14
        container_name: property-db
        restart: always
        mem_limit: 1g
        environment:
            POSTGRES_PASSWORD: root123
            POSTGRES_DB: db
            POSTGRES_USER: root
        volumes:
            - ../backend/pgdata:/var/lib/postgresql/data

    db-adminer:
        image: adminer
        container_name: property-adminer
        links:
            - db:db
        ports:
            - 7000:8080
        depends_on:
            - db

networks:
    default:
