version: '3.5'

services:
    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile
        container_name: property-backend

        ports:
            - '2000:2000'
        command: sh -c "npm install && npm start"

        volumes:
            - ../backend:/app
        depends_on:
            - db

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: property-frontend
        ports:
            - '3000:3000'
        command: sh -c "npm install &&  npm run dev"

        volumes:
            - ../frontend:/app

    db:
        image: mysql:latest
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: property_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: root123
        ports:
            - '6033:3306'
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 1000:80

volumes:
    dbdata:

networks:
    default:
